--<ScriptOptions statementTerminator=";"/>

CREATE TABLE DBSYS_LIST (
		DBNAME VARCHAR(30) NOT NULL,
		USERD VARCHAR(30) NOT NULL,
		PWD VARCHAR(30),
		DESCRIPTION VARCHAR(255),
		FILEPATH VARCHAR(255) NOT NULL
	);

CREATE UNIQUE INDEX INDEX1 ON DBSYS_LIST (DBNAME ASC);

CREATE UNIQUE INDEX SQL170401062510180 ON DBSYS_LIST (DBNAME ASC);

ALTER TABLE DBSYS_LIST ADD CONSTRAINT INDEX1 PRIMARY KEY (DBNAME);

